/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_proyectovinculacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JButton;
import javax.swing.JPanel;
import desplazable.Desface;

public class interfaz_dashboard extends javax.swing.JFrame {

    Desface desplace;
    Desface desplace2;

    interfaz_dashboard() {

        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        desplace = new Desface();
        desplace2 = new Desface();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new clasesDesing.PanelRound();
        pnlpegable = new clasesDesing.PanelRound();
        lbluser1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound3 = new clasesDesing.PanelRound();
        btnsalir = new javax.swing.JButton();
        btnusuario1 = new javax.swing.JButton();
        btnventas1 = new javax.swing.JButton();
        btnproducto1 = new javax.swing.JButton();
        btnproveedores1 = new javax.swing.JButton();
        lblcerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlinicio = new javax.swing.JPanel();
        lblconfiguracion = new javax.swing.JButton();
        lblinicio1 = new javax.swing.JButton();
        lblacercade = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbluser2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 23, 24));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(21, 21, 22));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        pnlpegable.setBackground(new java.awt.Color(12, 12, 12));
        pnlpegable.setPreferredSize(new java.awt.Dimension(283, 579));
        pnlpegable.setRoundBottomLeft(30);
        pnlpegable.setRoundBottomRight(50);
        pnlpegable.setRoundTopLeft(30);
        pnlpegable.setRoundTopRight(50);

        lbluser1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lbluser1.setForeground(new java.awt.Color(204, 204, 204));
        lbluser1.setText("User: Admin");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("DashBoard");

        panelRound3.setBackground(new java.awt.Color(0, 153, 153));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        btnsalir.setBackground(new java.awt.Color(153, 0, 0));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusPainted(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        btnusuario1.setBackground(new java.awt.Color(0, 0, 0));
        btnusuario1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnusuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnusuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/perfil1.png"))); // NOI18N
        btnusuario1.setText("   Usuario                   ");
        btnusuario1.setToolTipText("");
        btnusuario1.setBorder(null);
        btnusuario1.setBorderPainted(false);
        btnusuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuario1.setFocusPainted(false);
        btnusuario1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnusuario1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnusuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnusuario1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnusuario1MouseExited(evt);
            }
        });
        btnusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuario1ActionPerformed(evt);
            }
        });

        btnventas1.setBackground(new java.awt.Color(0, 0, 0));
        btnventas1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnventas1.setForeground(new java.awt.Color(255, 255, 255));
        btnventas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/familia.png"))); // NOI18N
        btnventas1.setText("   Familiares               ");
        btnventas1.setToolTipText("");
        btnventas1.setBorder(null);
        btnventas1.setBorderPainted(false);
        btnventas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnventas1.setFocusPainted(false);
        btnventas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnventas1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnventas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnventas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnventas1MouseExited(evt);
            }
        });
        btnventas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventas1ActionPerformed(evt);
            }
        });

        btnproducto1.setBackground(new java.awt.Color(0, 0, 0));
        btnproducto1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnproducto1.setForeground(new java.awt.Color(255, 255, 255));
        btnproducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estudiantes.png"))); // NOI18N
        btnproducto1.setText("   Estudiantes             ");
        btnproducto1.setToolTipText("");
        btnproducto1.setBorder(null);
        btnproducto1.setBorderPainted(false);
        btnproducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnproducto1.setFocusPainted(false);
        btnproducto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnproducto1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnproducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnproducto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnproducto1MouseExited(evt);
            }
        });
        btnproducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproducto1ActionPerformed(evt);
            }
        });

        btnproveedores1.setBackground(new java.awt.Color(0, 0, 0));
        btnproveedores1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnproveedores1.setForeground(new java.awt.Color(255, 255, 255));
        btnproveedores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fichas.png"))); // NOI18N
        btnproveedores1.setText("   Fichas                      ");
        btnproveedores1.setToolTipText("");
        btnproveedores1.setBorder(null);
        btnproveedores1.setBorderPainted(false);
        btnproveedores1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnproveedores1.setFocusPainted(false);
        btnproveedores1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnproveedores1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnproveedores1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnproveedores1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnproveedores1MouseExited(evt);
            }
        });
        btnproveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedores1ActionPerformed(evt);
            }
        });

        lblcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menup.png"))); // NOI18N
        lblcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcerrarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user2.png"))); // NOI18N

        javax.swing.GroupLayout pnlpegableLayout = new javax.swing.GroupLayout(pnlpegable);
        pnlpegable.setLayout(pnlpegableLayout);
        pnlpegableLayout.setHorizontalGroup(
            pnlpegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpegableLayout.createSequentialGroup()
                .addGroup(pnlpegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnusuario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlpegableLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcerrar))
                    .addComponent(btnproducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlpegableLayout.createSequentialGroup()
                        .addGroup(pnlpegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlpegableLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpegableLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lbluser1))
                            .addGroup(pnlpegableLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnventas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlpegableLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnproveedores1)))
                .addContainerGap())
        );
        pnlpegableLayout.setVerticalGroup(
            pnlpegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpegableLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlpegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lblcerrar))
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluser1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnusuario1)
                .addGap(32, 32, 32)
                .addComponent(btnproducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnproveedores1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnventas1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("DashBoard");

        pnlinicio.setBackground(new java.awt.Color(21, 21, 22));

        lblconfiguracion.setBackground(new java.awt.Color(24, 24, 24));
        lblconfiguracion.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblconfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        lblconfiguracion.setText("Configuracion");
        lblconfiguracion.setBorder(null);
        lblconfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblconfiguracion.setFocusPainted(false);
        lblconfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblconfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblconfiguracionMouseExited(evt);
            }
        });
        lblconfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblconfiguracionActionPerformed(evt);
            }
        });

        lblinicio1.setBackground(new java.awt.Color(24, 24, 24));
        lblinicio1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblinicio1.setForeground(new java.awt.Color(255, 255, 255));
        lblinicio1.setText("Inicio");
        lblinicio1.setBorder(null);
        lblinicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblinicio1.setFocusPainted(false);
        lblinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblinicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblinicio1MouseExited(evt);
            }
        });
        lblinicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblinicio1ActionPerformed(evt);
            }
        });

        lblacercade.setBackground(new java.awt.Color(24, 24, 24));
        lblacercade.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblacercade.setForeground(new java.awt.Color(255, 255, 255));
        lblacercade.setText("Acerca de");
        lblacercade.setBorder(null);
        lblacercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblacercade.setFocusPainted(false);
        lblacercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblacercadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblacercadeMouseExited(evt);
            }
        });
        lblacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblacercadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlinicioLayout = new javax.swing.GroupLayout(pnlinicio);
        pnlinicio.setLayout(pnlinicioLayout);
        pnlinicioLayout.setHorizontalGroup(
            pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlinicioLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(lblconfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblacercade)
                .addGap(26, 26, 26))
            .addGroup(pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlinicioLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lblinicio1)
                    .addContainerGap(181, Short.MAX_VALUE)))
        );
        pnlinicioLayout.setVerticalGroup(
            pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlinicioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconfiguracion)
                    .addComponent(lblacercade))
                .addContainerGap())
            .addGroup(pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlinicioLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(lblinicio1)
                    .addContainerGap()))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbluser2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lbluser2.setForeground(new java.awt.Color(204, 204, 204));
        lbluser2.setText("User: Admin");
        jPanel1.add(lbluser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 840, -1, 36));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 820, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logocolegio6.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 810, -1, -1));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(pnlpegable, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(pnlinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlpegable, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pnlinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        interfaz_iniciarSesion iniciarSesion = new interfaz_iniciarSesion();
        iniciarSesion.show();
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnusuario1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuario1MouseEntered
        btnusuario1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnusuario1MouseEntered

    private void btnusuario1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuario1MouseExited
        btnusuario1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnusuario1MouseExited

    private void btnusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuario1ActionPerformed
        
    }//GEN-LAST:event_btnusuario1ActionPerformed

    private void btnventas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventas1MouseEntered
        btnventas1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnventas1MouseEntered

    private void btnventas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventas1MouseExited
        btnventas1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnventas1MouseExited

    private void btnventas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventas1ActionPerformed
        
    }//GEN-LAST:event_btnventas1ActionPerformed

    private void btnproducto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproducto1MouseEntered
        btnproducto1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnproducto1MouseEntered

    private void btnproducto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproducto1MouseExited
        btnproducto1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnproducto1MouseExited

    private void btnproducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproducto1ActionPerformed
        
    }//GEN-LAST:event_btnproducto1ActionPerformed

    private void btnproveedores1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproveedores1MouseEntered
        btnproveedores1.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnproveedores1MouseEntered

    private void btnproveedores1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproveedores1MouseExited
        btnproveedores1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnproveedores1MouseExited

    private void btnproveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedores1ActionPerformed
        interfaz_submenufichasdos intervenciones = new interfaz_submenufichasdos();
        intervenciones.show();
    }//GEN-LAST:event_btnproveedores1ActionPerformed

    private void lblconfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblconfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblconfiguracionActionPerformed

    private void lblconfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconfiguracionMouseExited
        lblconfiguracion.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblconfiguracionMouseExited

    private void lblconfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconfiguracionMouseEntered
        lblconfiguracion.setForeground(new Color(255, 51, 0));
    }//GEN-LAST:event_lblconfiguracionMouseEntered

    private void lblinicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicio1MouseEntered
        lblinicio1.setForeground(new Color(255, 51, 0));
    }//GEN-LAST:event_lblinicio1MouseEntered

    private void lblinicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinicio1MouseExited
        lblinicio1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblinicio1MouseExited

    private void lblinicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblinicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblinicio1ActionPerformed

    private void lblacercadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblacercadeMouseEntered
        lblacercade.setForeground(new Color(255, 51, 0));
    }//GEN-LAST:event_lblacercadeMouseEntered

    private void lblacercadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblacercadeMouseExited
        lblacercade.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblacercadeMouseExited

    private void lblacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblacercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblacercadeActionPerformed
int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      
        xx=evt.getX();
        xy=evt.getY();
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void lblcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcerrarMouseClicked

        if (pnlpegable.getX() == 0) {
            desplace.desplazarIzquierda(pnlpegable, pnlpegable.getX(), -220, 10, 10);
            desplace2.desplazarIzquierda(pnlinicio, pnlinicio.getX(), 50, 10, 10);

        } else if (pnlpegable.getX() == -220) {
            desplace.desplazarDerecha(pnlpegable, pnlpegable.getX(), 0, 10, 10);
            desplace2.desplazarDerecha(pnlinicio, 0, 280, 13, 13);

        }
    }//GEN-LAST:event_lblcerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_dashboard().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproducto1;
    private javax.swing.JButton btnproveedores1;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnusuario1;
    private javax.swing.JButton btnventas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lblacercade;
    private javax.swing.JLabel lblcerrar;
    private javax.swing.JButton lblconfiguracion;
    private javax.swing.JButton lblinicio1;
    private javax.swing.JLabel lbluser1;
    private javax.swing.JLabel lbluser2;
    private clasesDesing.PanelRound panelRound1;
    private clasesDesing.PanelRound panelRound3;
    private javax.swing.JPanel pnlinicio;
    private clasesDesing.PanelRound pnlpegable;
    // End of variables declaration//GEN-END:variables

}
