/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_proyectovinculacion;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nekhross
 */
public class interfaz_fichaintervencion extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_listaventas
     */
    public interfaz_fichaintervencion() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        listarfichas();
    }

    public void listarfichas() {

        try {
            Conexion conexion = new Conexion();
            Statement st = conexion.conexion().createStatement();

            ResultSet rs = st.executeQuery("select * from fichaintervencion");

            DefaultTableModel tablamodelo = (DefaultTableModel) jtficha.getModel();
            tablamodelo.setColumnCount(0);
            tablamodelo.addColumn("ID DE LA FICHA");
            tablamodelo.addColumn("DESTINATARIO");
            tablamodelo.addColumn("AREAS");
            tablamodelo.addColumn("OBSERVACIONES");
            tablamodelo.addColumn("RESULTADOS");
            tablamodelo.setRowCount(0);

            while (rs.next()) {

                String[] registros = new String[5];
                registros[0] = rs.getString("id_ficha");
                registros[1] = rs.getString("destinatario");
                registros[2] = rs.getString("areas");
                registros[3] = rs.getString("observaciones");
                registros[4] = rs.getString("resultados");
                tablamodelo.addRow(registros);  
            }
            jtficha.setModel(tablamodelo);

        } catch (SQLException ex) {
            Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panelRound1 = new clasesDesing.PanelRound();
        panelRound2 = new clasesDesing.PanelRound();
        lbllogin2 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        lbllogin3 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        btnactualizarlista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtficha = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(63, 63, 63));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        panelRound2.setBackground(new java.awt.Color(24, 24, 24));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        lbllogin2.setBackground(new java.awt.Color(255, 255, 255));
        lbllogin2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lbllogin2.setForeground(new java.awt.Color(255, 255, 255));
        lbllogin2.setText("OPERACIONES ");

        btnregistrar.setBackground(new java.awt.Color(0, 153, 153));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrar.setText("REGISTRAR");
        btnregistrar.setBorder(null);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        lbllogin3.setBackground(new java.awt.Color(255, 255, 255));
        lbllogin3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lbllogin3.setForeground(new java.awt.Color(255, 255, 255));
        lbllogin3.setText("DE INTERVENCION");

        btnactualizar.setBackground(new java.awt.Color(0, 153, 153));
        btnactualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.setBorder(null);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(0, 153, 153));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(null);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneliminar1.setBackground(new java.awt.Color(0, 153, 153));
        btneliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar1.setText("CERRAR");
        btneliminar1.setBorder(null);
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        btnactualizarlista.setBackground(new java.awt.Color(0, 153, 153));
        btnactualizarlista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnactualizarlista.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizarlista.setText("ACTUALIZAR LISTA");
        btnactualizarlista.setBorder(null);
        btnactualizarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarlistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogin3)
                            .addComponent(lbllogin2)))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnactualizarlista, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbllogin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllogin3)
                .addGap(72, 72, 72)
                .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnactualizarlista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jtficha.setBackground(new java.awt.Color(204, 204, 204));
        jtficha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtficha);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

        interfaz_registrointervenciones registroProductos = new interfaz_registrointervenciones();
        registroProductos.btnregistrar.setEnabled(true);
        registroProductos.btnactualizar.setEnabled(false);
        registroProductos.btnactualizar.setText("NO DISPONIBLE");
        registroProductos.lblid.setVisible(false);
        registroProductos.lbltituloid.setVisible(false);
        registroProductos.show();
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        int fila = jtficha.getSelectedRow();

        String id_ficha = (String) jtficha.getValueAt(fila, 0);
        String destinatario = (String) jtficha.getValueAt(fila, 1);
        String areas = (String) jtficha.getValueAt(fila, 2);
        String areas2 = (String) jtficha.getValueAt(fila, 2);
        String observaciones = (String) jtficha.getValueAt(fila, 3);
        String resultados = (String) jtficha.getValueAt(fila, 4);
        interfaz_registrointervenciones registroficha = new interfaz_registrointervenciones();

        registroficha.cmbdestinatario.setSelectedItem(destinatario);
        registroficha.cmbdestinatario.setSelectedItem(areas);
        registroficha.txtotro.setText(areas2);
        registroficha.txtobservaciones.setText(observaciones);
        registroficha.txtresultados.setText(resultados);
       
        listarfichas();
        registroficha.btnactualizar.setEnabled(true);
        registroficha.btnregistrar.setEnabled(false);
        registroficha.btnregistrar.setText("NO DISPONIBLE");
        registroficha.lblid.setText(id_ficha);

        registroficha.show();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {

            int fila = jtficha.getSelectedRow();
            String id_ficha = (String) jtficha.getValueAt(fila, 0);
            Conexion conexion = new Conexion();
            Statement st = conexion.conexion().createStatement();
            st.execute("delete from fichaintervencion where id_ficha = '" + id_ficha + "';");
            JOptionPane.showMessageDialog(this, "ELIMINADO CORRECTAMENTE");
         

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "HA OCURRIDO UN ERROR");
            Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void btnactualizarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarlistaActionPerformed
        listarfichas();
    }//GEN-LAST:event_btnactualizarlistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_fichaintervencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_fichaintervencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnactualizarlista;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtficha;
    private javax.swing.JLabel lbllogin2;
    private javax.swing.JLabel lbllogin3;
    private clasesDesing.PanelRound panelRound1;
    private clasesDesing.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
